server:
  port: 8083

spring:
#  application:
#    name: inventory-service
  datasource:
#    url: jdbc:mysql://inventory-db:3306/inventory_db
    url: jdbc:mysql://localhost:3308/inventory_db # change
    username: root
    password: 12122005
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

security:
  jwt:
    secret: ${JWT_SECRET:your_new_and_very_long_and_very_secure_secret_key_that_is_at_least_32_characters_long}
    issuer: "erp-auth"

app:
  cors:
    allowed-origins: "http://localhost:5173"